states:
  # Main flow
  A:
    name: A
    onEnter:
      - logAction
    transitions:
      - event: next
        target: B
  B:
    name: B
    onEnter:
      - logAction
    transitions:
      - event: next
        target: C
  C:
    name: C
    onEnter:
      - logAction
    transitions:
      - event: next
        target: D
      - event: sideQuestB
        target: B#
        actions:
          - recordPreviousState
  D:
    name: D
    onEnter:
      - logAction
    transitions:
      - event: next
        target: E
      - event: sideQuestB
        target: B#
        actions:
          - recordPreviousState
      - event: sideQuestC
        target: C#
        actions:
          - recordPreviousState
  E:
    name: E
    onEnter:
      - logAction
    transitions:
      - event: next
        target: F
      - event: sideQuestB
        target: B#
        actions:
          - recordPreviousState
      - event: sideQuestC
        target: C#
        actions:
          - recordPreviousState
  F:
    name: F
    onEnter:
      - logAction
    transitions:
      - event: next
        target: G
      - event: sideQuestC
        target: C#
        actions:
          - recordPreviousState
  G:
    name: G
    onEnter:
      - logAction
  # Side quests
  B#:
    name: B#
    onEnter:
      - logAction
    transitions:
      - event: return
        target: ""  # Dynamic target
        actions:
          - __RETURN_TO_PREVIOUS_STATE__
  C#:
    name: C#
    onEnter:
      - logAction
    transitions:
      - event: return
        target: ""  # Dynamic target
        actions:
          - __RETURN_TO_PREVIOUS_STATE__