states:
  start:
    name: start
    onEnter:
      - "logStart"
    transitions:
      - event: "validate"
        target: "processOrder"
        conditions:
          - "isUserValid"

  processOrder:
    name: processOrder
    onEnter:
      - "logProcessing"
    transitions:
      - event: "process"
        target: "complete"
        actions:
          - "chargePayment"
        conditions:
          - "isPaymentSuccess"
      - event: "fail"
        target: "failed"
        actions:
          - "handleFailure"

  complete:
    name: complete
    onEnter:
      - "logCompletion"
      - "sendReceipt"

  failed:
    name: failed
    onEnter:
      - "logFailure"